name: Deploy Next.js site to Pages
env:
  NEXT_PUBLIC_GIVEBUTTER_ID: ${{ vars.NEXT_PUBLIC_GIVEBUTTER_ID}
  NEXT_PUBLIC_CONTACT_EMAIL: ${{ vars.NEXT_PUBLIC_CONTACT_EMAIL}
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${{ vars.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
  NEXT_PUBLIC_SOCIALS_INSTAGRAM: ${{ vars.NEXT_PUBLIC_SOCIALS_INSTAGRAM}
  NEXT_PUBLIC_SOCIALS_BLUESKY: ${{ vars.NEXT_PUBLIC_SOCIALS_BLUESKY}
  NEXT_PUBLIC_SOCIALS_FACEBOOK: ${{ vars.NEXT_PUBLIC_SOCIALS_FACEBOOK}
  NEXT_PUBLIC_SOCIALS_LINKEDIN: ${{ vars.NEXT_PUBLIC_SOCIALS_LINKEDIN}
  NEXT_PUBLIC_SOCIALS_THREADS: ${{ vars.NEXT_PUBLIC_SOCIALS_THREADS}
on:
  push:
    branches:
      - main
  workflow_dispatch: null
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json',
            '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: >
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json',
            '**/yarn.lock') }}-
      - name: Install dependencies
        run: bun install
      - name: Build with Next.js
        run: bun run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
